import Head from "next/head";
import Image from "next/image";
import Header from "components/Header";
import Hero from "components/Hero";
import About from "components/About";
import Experience from "components/Experience";
import Skills from "components/Skills";

export default function Home() {
  return (
    <>
      <Head>
        <title>Chris Stewart Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className="bg-zinc-800 text-white h-screen snap-y snap-mandatory overflow-scroll z-0">
          <Header />
          <section id='hero' className="snap-start">
            <Hero />
          </section>
          <section id='about' className="snap-center">
            <About />
          </section>
          <section id='experience' className="snap-center">
            <Experience />
          </section>
          <section id='skills' className="snap-center">
            <Skills />
          </section>
          {/* Projects */}

          {/* Contact */}

        </div>
      </main>

    </>
  );
}


